name: cxhub_sdk_example
description: "Demonstrates how to use the cxhub_sdk plugin."
publish_to: https://onepub.dev/api/afhaavuhno
homepage: https://gitlab.corp.mail.ru/cxhub1/flutter-sdk
repository: https://gitlab.corp.mail.ru/cxhub1/flutter-sdk

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cxhub_sdk: 0.0.1
  cupertino_icons: ^1.0.6

dependency_overrides:
## Uncomment needed part to switch to huawei|rustore implementation
## default is firebase
#  cxhub_android: 0.0.1-huawei
#  cxhub_android: 0.0.1-rustore

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true