# Uncomment this line to define a global platform for your project

platform :ios, '15.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)
  
  target 'Runner' do
    use_frameworks!
    use_modular_headers!
    flutter_install_all_ios_pods  File.dirname(File.realpath(__FILE__))
      target 'RunnerTests' do
        inherit! :search_paths
      end
  end


  target 'ServiceExtension' do
    use_frameworks!
    use_modular_headers!
    #flutter_install_all_ios_pods  File.dirname(File.realpath(__FILE__))
    flutter_install_ios_engine_pod File.dirname(File.realpath(__FILE__))
    pod 'cxhub_ios', path: '.symlinks/plugins/cxhub_ios/ios'
  end

  target 'ContentExtension' do
    use_frameworks!
    use_modular_headers!
    #flutter_install_all_ios_pods  File.dirname(File.realpath(__FILE__))
    flutter_install_ios_engine_pod File.dirname(File.realpath(__FILE__))
    pod 'cxhub_ios', path: '.symlinks/plugins/cxhub_ios/ios'
  end

#post_install do |installer|
#  installer.pods_project.targets.each do |target|
#    flutter_additional_ios_build_settings(target)
#  end
#end
  post_install do |installer|
    
    installer.pods_project.targets.each do |target|
      flutter_additional_ios_build_settings(target)
      
      if target == 'Runner' then 
        #flutter_additional_ios_build_settings(target)
        target.build_configurations.each do |config|
          config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
            '$(inherited)',
            ## dart: PermissionGroup.notification
            'PERMISSION_NOTIFICATIONS=1'
          ]
        end
      end
      
      target.build_configurations.each do |config|
        config.build_settings['CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER'] ||= [
          '$(inherited)'
        ]
        config.build_settings['ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES'] ||= [
          '$(inherited)'
        ]
      end

    end
  end
