name: cxhub_android
description: "Android platform implementation for cxhub_sdk"
version: 0.0.1-firebase
publish_to: https://onepub.dev/api/ndfuuhnofl
homepage: https://gitlab.corp.mail.ru/cxhub1/flutter-sdk
repository: https://gitlab.corp.mail.ru/cxhub1/flutter-sdk

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: '>=3.3.0'

flutter:
  plugin:
    implements: cxhub_sdk
    platforms:
      android:
        package: plugin.cxhub_sdk
        pluginClass: CxHubSdkPluginFirebase
        dartPluginClass: CxHubSdkPlatformAndroid

dependencies:
  flutter:
    sdk: flutter
  cxhub_platform_interface:
    hosted: https://onepub.dev/api/ndfuuhnofl
    version: 0.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
