name: cxhub_android
description: "Android platform implementation for cxhub_sdk"
version: 0.0.2-rustore

homepage: https://cxhub.ru
repository: https://github.com/cxhub-corp/flutter_cxhub_sdk/tree/publish/cxhub_android_rustore

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: '>=3.3.0'

flutter:
  plugin:
    implements: cxhub_sdk
    platforms:
      android:
        package: plugin.cxhub_sdk
        pluginClass: CxHubSdkPluginRuStore
        dartPluginClass: CxHubSdkPlatformAndroid

dependencies:
  flutter:
    sdk: flutter
  cxhub_platform_interface: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
